name: Test MATLAB MEX on macOS and Windows

on:
  # Trigger the workflow on push or pull request
  push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
      - cron: '0 19 * * *'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test MATLAB MEX on macOS and Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Fortran
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: 11

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.1.0

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: |
              mex('-setup', '-v', 'C'); mex('-v', fullfile(matlabroot, 'extern', 'examples', 'refbook', 'timestwo.c')); timestwo(1); delete('timestwo.mex*');
              mex('-setup', '-v', 'FORTRAN'); mex('-v', fullfile(matlabroot, 'extern', 'examples', 'refbook', 'timestwo.F')); timestwo(1); delete('timestwo.mex*');
